version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-dashboards/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: kibana:8.11.3
    container_name: kibana
    ports:
      - "5601:5601"
